basePath = "Interface\\AddOns\\TwitchEmotes_Coomer\\emotes\\";
TwitchEmotes_animation_metadata[basePath .. "peepoRun.tga"] = {["nFrames"] = 6, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 18};
TwitchEmotes_animation_metadata[basePath .. "donkWalk.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "catPls.tga"] = {["nFrames"] = 30, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Cooking.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "SCHIZO.tga"] = {["nFrames"] = 71, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 45}
TwitchEmotes_animation_metadata[basePath .. "catYep.tga"] = {["nFrames"] = 2, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 64, ["framerate"] = 14}
TwitchEmotes_animation_metadata[basePath .. "catNope.tga"] = {["nFrames"] = 2, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 64, ["framerate"] = 14}
TwitchEmotes_animation_metadata[basePath .. "LETSFUCKINGSHIT.tga"] = {["nFrames"] = 11, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "GAMBA.tga"] = {["nFrames"] = 29, ["frameWidth"] = 32, ["frameHeight"] = 27, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "clam.tga"] = {["nFrames"] = 8, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 12}
TwitchEmotes_animation_metadata[basePath .. "THEVOICES.tga"] = {["nFrames"] = 45, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "ppOverheat.tga"] = {["nFrames"] = 8, ["frameWidth"] = 32, ["frameHeight"] = 28, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "HECOOKING.tga"] = {["nFrames"] = 38, ["frameWidth"] = 32, ["frameHeight"] = 31, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "THINKING.tga"] = {["nFrames"] = 26, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "treeDance.tga"] = {["nFrames"] = 53, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 20}
TwitchEmotes_animation_metadata[basePath .. "GAGGERS.tga"] = {["nFrames"] = 16, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "awaree.tga"] = {["nFrames"] = 16, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 6}
TwitchEmotes_animation_metadata[basePath .. "Joeling.tga"] = {["nFrames"] = 8, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 24}
TwitchEmotes_animation_metadata[basePath .. "donut.tga"] = {["nFrames"] = 2, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 64, ["framerate"] = 12}
TwitchEmotes_animation_metadata[basePath .. "MushroomNow.tga"] = {["nFrames"] = 2, ["frameWidth"] = 32, ["frameHeight"] = 29, ["imageWidth"] = 32, ["imageHeight"] = 64, ["framerate"] = 12}
TwitchEmotes_animation_metadata[basePath .. "PETTHESHROOM.tga"] = {["nFrames"] = 5, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Catting.tga"] = {["nFrames"] = 3, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 128, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "rofl.tga"] = {["nFrames"] = 32, ["frameWidth"] = 32, ["frameHeight"] = 26, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "OrangeJustice.tga"] = {["nFrames"] = 78, ["frameWidth"] = 29, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Pivo.tga"] = {["nFrames"] = 124, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "jupijej.tga"] = {["nFrames"] = 16, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "obliteratedthanaho.tga"] = {["nFrames"] = 134, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "buh.tga"] = {["nFrames"] = 98, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "slam.tga"] = {["nFrames"] = 57, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 14}
TwitchEmotes_animation_metadata[basePath .. "pepeRun2.tga"] = {["nFrames"] = 17, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "UHMM.tga"] = {["nFrames"] = 2, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 64, ["framerate"] = 0.66}
TwitchEmotes_animation_metadata[basePath .. "YAPP.tga"] = {["nFrames"] = 2, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 64, ["framerate"] = 12}
TwitchEmotes_animation_metadata[basePath .. "boobaCheck.tga"] = {["nFrames"] = 28, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "obliteratedthanaho.tga"] = {["nFrames"] = 134, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 21}
TwitchEmotes_animation_metadata[basePath .. "REDDERS.tga"] = {["nFrames"] = 4, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 128, ["framerate"] = 20}
TwitchEmotes_animation_metadata[basePath .. "BLUERS.tga"] = {["nFrames"] = 16, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 80}
TwitchEmotes_animation_metadata[basePath .. "OhGodItsMoonMoonChasingYouThroughTheBorealWinterPLEASERUNQUICKLYANDFINDCOVERHEHASBADINTENTIONS.tga"] = {["nFrames"] = 157, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 27}
TwitchEmotes_animation_metadata[basePath .. "IVEGONEPASTTHEPOINTOFINSANITY.tga"] = {["nFrames"] = 80, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "redPls.tga"] = {["nFrames"] = 8, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 12}
TwitchEmotes_animation_metadata[basePath .. "bluePls.tga"] = {["nFrames"] = 255, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 36}
TwitchEmotes_animation_metadata[basePath .. "COGGERS.tga"] = {["nFrames"] = 30, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "COUNTERCOGGERS.tga"] = {["nFrames"] = 30, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "brainsmash.tga"] = {["nFrames"] = 14, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Floreda.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "aaAAAAAaaaaaaaAAAAAaaaaaaaAAAAAa.tga"] = {["nFrames"] = 3, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 128, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "NEOW.tga"] = {["nFrames"] = 90, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "glorpShakey.tga"] = {["nFrames"] = 16, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "NOW.tga"] = {["nFrames"] = 90, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Dentging.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "bearWalk.tga"] = {["nFrames"] = 13, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Wha.tga"] = {["nFrames"] = 16, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 12}
TwitchEmotes_animation_metadata[basePath .. "glorpSlam.tga"] = {["nFrames"] = 38, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Glizzy.tga"] = {["nFrames"] = 150, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "peepoDrill.tga"] = {["nFrames"] = 6, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 12}
