basePath = "Interface\\AddOns\\TwitchEmotes_Coomer\\emotes\\"

judhead_emotes = {
    -- Coomer Specfic Memes
    ["judhead"] = basePath .. "judhead.tga:28:28",
    ["ResidentJud"] = basePath .. "ResidentJud.tga:28:28",
    ["sebg"] = basePath .. "sebg.tga:28:28",
    ["makback"] = basePath .. "makback.tga:28:28",
    ["abigail"] = basePath .. "abigail.tga:28:28",
    ["frontalfan"] = basePath .. "frontalfan.tga:28:28",
    -- General Memes
    ["Life"] = basePath .. "Life.tga:28:28",
    ["Death"] = basePath .. "Death.tga:28:28",
    ["gotme"] = basePath .. "gotme.tga:28:28",
    ["catErm"] = basePath .. "catErm.tga:28:28",
    ["cheeky"] = basePath .. "cheeky.tga:28:28",
    ["DRATTY"] = basePath .. "DRATTY.tga:28:28",
    ["Fiddy"] = basePath .. "Fiddy.tga:28:28",
    ["garf"] = basePath .. "garf.tga:28:28",
    ["frag"] = basePath .. "frag.tga:28:28",
    ["LetHimCook"] = basePath .. "LetHimCook.tga:28:28",
    ["Stare"] = basePath .. "Stare.tga:28:28",
    ["catEhm"] = basePath .. "catEhm.tga:28:28",
    ["cumby"] = basePath .. "cumby.tga:28:28",
    ["Looking"] = basePath .. "Looking.tga:28:28",
    ["peepoRun"] = basePath .. "peepoRun.tga:28:28",
    ["donkWalk"] = basePath .. "donkWalk.tga:28:28",
    ["Chatter"] = basePath .. "Chatter.tga:28:28",
    ["catPls"] = basePath .. "catPls.tga:28:28",
    ["FeelsWeakMan"] = basePath .. "FeelsWeakMan.tga:28:28",
    ["Cooking"] = basePath .. "Cooking.tga:28:28",
    ["MONKE"] = basePath .. "MONKE.tga:28:28",
    ["SCHIZO"] = basePath .. "SCHIZO.tga:28:28",
    ["catYep"] = basePath .. "catYep.tga:28:28",
    ["catNope"] = basePath .. "catNope.tga:28:28",
}
